### ISSUE TITLE
Enhancement: Capture errors from Mocking APIs

### ISSUE THREAD

**Issue by cernertrevor** [cerner/cclunit-framework#20]
Currently, CCL resets the error stack whenever a child script is executed with the "execute" command.  This could lead to errors being suppressed in a unit test if the error occurs before "execute" is invoked.  An example of this would be if an error occurred while trying to create a mock table with cclutDefineMockTable and then the script-under-test is called using cclutExecuteProgramWithMocks.

Because the Mocking APIs provide an abstraction for "execute" now (cclutExecuteProgramWithMocks), the framework would be capable of checking for any errors in the error stack and documenting them, so that the test can fail even if all assertions pass (similar to what the cclutAssert* subroutines do).  In fact, all of the Mocking APIs could support it to provide more information to the consumer about any errors in their unit test.

This issue is to implement this enhancement.

**Comment by feckertson** [comment]
This is actually a defect. CCL Unit should report any identifiable errors. Any error created by the mocking framework is identifiable but not all of them are reported.  Below is a test to illustrate where sample_script is any program that does not produce an error. The add mock implementation call causes an error but it does not get reported.

subroutine test_it(null)
    call cclutAddMockImplementation("yo","")
    call cclutExecuteProgramWithMocks("sample_script")
end

**Comment by cernertrevor** [comment]
The only thing I'm wondering about is do we need to have _every_ Mocking API function do the stashErrors check.  Theoretically, the following subroutine would also generate an error that goes unreported:

```
subroutine test_it(null)
call cclutAddMockImplementation("yo","")
execute sample_script
end
```

Yes, this is par for the course for CCL (resetting the error stack when "execute" is called), but since cclutAddMockImplementation is a framework function, it could stash the errors before returning control so that the user can't accidentally reset it by executing a program.  I realize the example above is somewhat contrived as we should be expecting consumers to utilize cclutExecuteProgramWithMocks if they're using any of the Mocking API functions; however, I still feel the question is worth asking.

A slightly less contrived example might be if somebody sets up an executable program to do some initialization that _isn't_ using cclutExecuteProgramWithMocks (because such an initialization script is not the script-under-test).

```
subroutine test_it(null)
record my_structure (
    ;fields
)
call cclutAddMockImplementation("my_structure","") ;mistake in adding my_structure
execute fill_my_structure_test_data ;a local prg for populating the record structure with test data - could take parameters for other tests in the same suite
call cclutExecuteProgramWithMocks("sample_script") ;actual script under test
end
```

Once again, there could be other arguments made against such patterns (e.g. "populating test record structures should take place in subroutines within the test suite instead of a separate executable program"), but I'm just speculating about different use cases.
