### ISSUE TITLE
Is mocking of service calls available in this feature?

### ISSUE THREAD

**Issue by Paresh319** [cerner/cclunit-framework#37]
So I would like to write tests for a piece of code which calls a service which in turn fetches data from two tables. Is there a way I can write tests using mocking api for something like this.

**Comment by feckertson** [comment]
Mock the service call. 
... and test that the code responds correctly to various responses from the service call.

The fact that the service reads the database should be irrelevant. It is a service. Its consumers and their tests should be written without concern about where/how the service works.
